fixtures:
  repositories:
    apache_c2c: 'https://github.com/camptocamp/puppet-apache_c2c.git'
  forge_modules:
    concat:
      repo: 'puppetlabs-concat'
      ref: '1.1.2'
    stdlib: 'puppetlabs-stdlib'
  symlinks:
    php: "#{source_dir}"
